import { useCallback, useEffect, useMemo, useState } from 'react'
import type { ReactNode } from 'react'
import type { ProjectOverview, Task } from '../../shared/contract.js'
import { projectControlState } from '../../shared/project-control.js'
import { FOCUS_KEY, projectDecisionItems, projectPulseSignal } from '../../shared/project-signals.js'
import { project as projectApi } from '../ipc.js'
import { ACTIVE_PROJECT, FINISHED_PROJECT, SHELVED_PROJECT } from '../../shared/vocabulary.js'
import { useBanner, useJump, useToast, useToday, useVaultRevision } from '../shell/AppShell.js'
import { FloatingTextEditor } from '../components/FloatingTextEditor.js'
import { Icon } from '../components/icons.js'
import { EmptyState } from '../components/EmptyState.js'
import { StructuredList, StructuredRow } from '../components/StructuredList.js'
import { dnum } from '../../shared/dates.js'
import { useFormat } from '../lib/format.js'
import { useMessages } from '../messages/useMessages.js'
import {
  EventText, ProjectSignalDate, ProjectSignalKind,
} from '../components/project/ProjectSignals.js'
import { ProjectNextActionView } from '../components/project/ProjectControl.js'
import { ProjectIdentity } from '../components/project/ProjectIdentity.js'
import { DAY_SLOT_HOURS } from '../components/timeline/TimelineScale.js'
import { TimelineBoard } from '../components/timeline/TimelineBoard.js'
import type { TimelinePoint } from '../components/timeline/TimelineBoard.js'
import { useVaultWrite } from '../hooks/useVaultWrite.js'
import {
  PageBody, PageError, PageHeader, PageShell, PageTitle, SectionHeading,
} from '../components/PageShell.js'
import './shell.css'
import './ResearchOverview.css'

/** The maximum number of recent progress items can be listed, which is the same as the demo’s recentHTML. */
const RECENT_EVENTS = 6
/** Scientific research records within this many days are counted as "advancement in the past 7 days." */
const WEEK_DAYS = 7

/** The milestone layer opened on Gantt: create a new one on a certain day, or change a certain one. `left`/`top` are coordinates within the canvas. */
type MilestonePop =
  | { kind: 'new'; projectId: string; date: string; left: number; top: number }
  | {
    kind: 'edit'; projectId: string; milestoneId: string; date: string; title: string
    left: number; top: number
  }

/** Numeric summary: See scale and health at a glance, same as demo's statHTML. */
function Stats({ rows }: { rows: ProjectOverview[] }) {
  const today = dnum(useToday())
  const m = useMessages()
  const count = (status: string) => rows.filter((p) => p.status === status).length
  const sum = (of: (p: ProjectOverview) => number) => rows.reduce((n, p) => n + of(p), 0)
  const recent = (date: string) => {
    const distance = today - dnum(date)
    return distance >= 0 && distance < WEEK_DAYS
  }
  const stats: { value: number; label: string; bad?: boolean }[] = [
    { value: count(ACTIVE_PROJECT), label: m.research.overview.stats.active },
    { value: count(SHELVED_PROJECT), label: m.research.overview.stats.shelved },
    {
      value: sum((p) => p.milestones.filter((x) => !x.done).length),
      label: m.research.overview.stats.openMilestones,
    },
    {
      value: sum((p) => p.events.filter((event) => recent(event.date)).length),
      label: m.research.overview.stats.recentProgress,
    },
  ]
  return (
    <div className="ovstats">
      {stats.map((s) => (
        <div className={s.bad ? 'ovstat bad' : 'ovstat'} key={s.label}>
          <b>{s.value}</b><span>{s.label}</span>
        </div>
      ))}
    </div>
  )
}

/**
 * Each column in the overview shares the same reading order: Project/Time/Type/Main Content/Auxiliary Status.
 * Dates are generated by OverviewDate, and milestones maintain the same expression in the decision queue and "Next".
 */
function OverviewList({ children }: { children: ReactNode }) {
  return <StructuredList className="ovlist project-signal-columns" variant="embedded">{children}</StructuredList>
}

function OverviewDate({ date }: { date: string | undefined }) {
  return <ProjectSignalDate date={date} />
}

function OverviewRow({ when, kind, main, meta, project, projectId, variant, onOpen }: {
  when?: ReactNode
  kind: ReactNode
  main: ReactNode
  meta?: ReactNode
  project: string
  projectId: string
  variant: 'attention' | 'progress' | 'dated'
  onOpen: () => void
}) {
  return (
    <StructuredRow className={`ovlist-row ${variant}`} data-proj={projectId} onActivate={onOpen}>
      <span className="ovlist-project" title={project}>{project}</span>
      <span className="ovlist-when">{when}</span>
      <span className="ovlist-kind">{kind}</span>
      <span className="ovlist-main">{main}</span>
      {meta ? <span className="ovlist-meta">{meta}</span> : null}
    </StructuredRow>
  )
}

/** Decision required: cross-project signals are merged and sorted, and the next action is directly explained on the right side. */
function DecisionQueue({ rows, onOpen }: {
  rows: ProjectOverview[]; onOpen: (projectId: string) => void
}) {
  const today = useToday()
  const m = useMessages()
  const items = rows.flatMap((project) => projectDecisionItems({
    ...project,
    // Old project conclusions are no longer product features, compatibility data is retained but is not projected into an overview decision.
    conclusions: { conflicting: 0 },
  }, today, m.project.signals)
    .map((item) => ({ ...item, projectId: project.id, name: project.name })))
    .sort((a, b) => a.rank - b.rank || dnum(a.date ?? today) - dnum(b.date ?? today))
  if (items.length === 0) return null
  return (
    <>
      <SectionHeading>{m.research.overview.decisions(items.length)}</SectionHeading>
      <OverviewList>
        {items.map((x) => (
          <OverviewRow
            key={`${x.projectId}${x.id}`}
            variant="attention"
            when={<OverviewDate date={x.date} />}
            kind={<ProjectSignalKind tone={x.tone}>{x.kind}</ProjectSignalKind>}
            main={x.reason}
            meta={<span className="ovdecision-action">{x.action} →</span>}
            project={x.name}
            projectId={x.projectId}
            onOpen={() => onOpen(x.projectId)}
          />
        ))}
      </OverviewList>
    </>
  )
}

/**
 * Project progress: One line answers what a project is currently doing, what just happened, what is the next step, and where intervention is needed.
 * These are deterministic projections of existing tasks/milestones/research records, without calling LLM or reversely modifying the research map.
 */
function ProjectProgress({ rows, onOpen }: {
  rows: ProjectOverview[]; onOpen: (projectId: string) => void
}) {
  const today = useToday()
  const m = useMessages()
  const current = rows.filter((project) => project.status !== FINISHED_PROJECT)
  return (
    <>
      <SectionHeading>{m.research.overview.progressHeading}</SectionHeading>
      {current.length === 0
        ? (
          <EmptyState variant="page" icon={<Icon sw={1.4}><path d="M20 6L9 17l-5-5" /></Icon>}>
            {m.research.overview.empty}
          </EmptyState>
        )
        : (
          <StructuredList className="ovpulse" variant="embedded">
            {current.map((project) => {
              const control = projectControlState({
                tasks: project.tasks,
                ...(project.block === undefined ? {} : { block: project.block }),
                activeNodes: project.research.activeNodes,
              })
              const active = control.next.source === 'task' && control.next.task.state === 'act'
                ? control.next.task
                : undefined
              const activeCount = project.tasks.filter((task) => task.state === 'act').length
              const latest = [...project.events].sort((a, b) => dnum(b.date) - dnum(a.date))[0]
              const signal = projectPulseSignal({
                ...project, conclusions: { conflicting: 0 },
              }, today, m.project.signals)
              const [firstActive, ...moreActive] = project.research.activeNodes
              const activeLabel = firstActive === undefined
                ? undefined
                : moreActive.length === 0
                  ? firstActive.label
                  : `${firstActive.label} ${m.research.overview.activeNodesMore(moreActive.length)}`
              const activeTitle = project.research.activeNodes.map((n) => n.label).join(', ')
              return (
                <StructuredRow
                  className="ovlist-row progress ovpulse-row" data-proj={project.id}
                  key={project.id} onActivate={() => onOpen(project.id)}
                >
                  <ProjectIdentity project={project} variant="progress" />
                  <span className="ovpulse-cell">
                    <b title={activeLabel === undefined ? project.focus : activeTitle}>
                      {activeLabel ?? project.focus}
                    </b>
                    <span className="ovpulse-sub">
                      {firstActive
                        ? m.research.overview.activePathNote(active ? control.next.text : undefined)
                        : (() => {
                          const label = m.project.identity.focusLabel[FOCUS_KEY[project.status]]
                          return active
                            ? m.research.overview.focusWithActiveTasks(label, activeCount)
                            : label
                        })()}
                    </span>
                  </span>
                  <span className="ovpulse-cell">
                    <b title={latest?.text}>
                      {latest ? <EventText text={latest.text} /> : m.research.overview.noRecentRecord}
                    </b>
                    <span className="ovpulse-sub">
                      {latest ? <OverviewDate date={latest.date} /> : m.research.overview.waitingForAgent}
                    </span>
                  </span>
                  <span className="ovpulse-cell">
                    <ProjectNextActionView action={control.next} variant="summary" />
                  </span>
                  <span className="ovpulse-cell signal">
                    <span className={`ovpulse-signal ${signal.tone}`}>{signal.label}</span>
                    <span className="ovpulse-sub" title={signal.detail}>{signal.detail}</span>
                  </span>
                </StructuredRow>
              )
            })}
          </StructuredList>
        )}
    </>
  )
}

/** Recent progress: Scientific research records of all projects are merged in reverse order to answer "what happened when I was away". */
function Recent({ rows, onOpen }: { rows: ProjectOverview[]; onOpen: (projectId: string) => void }) {
  const m = useMessages()
  const events = rows
    .flatMap((p) => p.events.map((e) => ({ ...e, projectId: p.id, name: p.name })))
    .sort((a, b) => dnum(b.date) - dnum(a.date))
    .slice(0, RECENT_EVENTS)
  return (
    <>
      <SectionHeading>{m.research.overview.recentHeading}</SectionHeading>
      <OverviewList>
        {events.map((e) => {
          return (
            <OverviewRow
              key={`${e.projectId}${e.date}${e.text}`}
              variant="dated"
              when={<OverviewDate date={e.date} />}
              kind={<ProjectSignalKind tone="mut">{m.research.overview.eventKind}</ProjectSignalKind>}
              main={<EventText text={e.text} />}
              project={e.name}
              projectId={e.projectId}
              onOpen={() => onOpen(e.projectId)}
            />
          )
        })}
      </OverviewList>
    </>
  )
}

/** Next milestones: Those that are not completed in the entire project and are no earlier than today, ordered by date from most recent to most recent. */
function Upcoming({ rows, onOpen }: { rows: ProjectOverview[]; onOpen: (projectId: string) => void }) {
  const todayIso = useToday()
  const today = dnum(todayIso)
  const m = useMessages()
  const items = rows
    .flatMap((p) => p.milestones.filter((x) => !x.done).map((x) => ({ ...x, projectId: p.id, name: p.name })))
    .filter((x) => dnum(x.date) >= today)
    .sort((a, b) => dnum(a.date) - dnum(b.date))
  return (
    <>
      <SectionHeading>{m.research.overview.upcomingHeading}</SectionHeading>
      <OverviewList>
        {items.map((x) => (
            <OverviewRow
              key={`${x.projectId}${x.id}`}
              variant="dated"
              when={<OverviewDate date={x.date} />}
              kind={<ProjectSignalKind tone="warn">{m.project.plan.milestoneMode}</ProjectSignalKind>}
              main={x.title}
              project={x.name}
              projectId={x.projectId}
              onOpen={() => onOpen(x.projectId)}
            />
        ))}
      </OverviewList>
    </>
  )
}

/**
 * Full project timeline: Each project first draws a milestone path, and then expands it task by task and line by line.
 * The horizontal bar is the real date/time window of the task, and the project start/due is no longer drawn as a fake task.
 * Drag the horizontal bar to change the task time, drag the diamond to change the milestone date; without dragging, just click the task to enter the project, and just click the diamond to open the editing popup.
 * All task rows are retained when switching day/week/month; when the task is outside the current window, only the edge stumps are harvested, and the entire row will not disappear.
 * Enter in the pop-up layer: put it away after you have finished writing. When you write that you are rejected, the pop-up layer and the typed words are kept; when you write on the road, the bullet layer is moved to another place, this time it is written
 * Nor will the one who moved over be taken away. Press Esc to close the focus on any element in the popup layer. `onRenameMilestone` with
 * `onNewMilestone` returns whether it was written this time.
 */
function OverviewGantt({
  rows, onOpenProject, onOpenTask, onMoveTask, onMoveTaskWindow, onMoveMilestone, onRenameMilestone,
  onDeleteMilestone, onNewMilestone,
}: {
  rows: ProjectOverview[]
  onOpenProject: (projectId: string) => void
  onOpenTask: (projectId: string, taskId: string) => void
  onMoveTask: (
    projectId: string, taskId: string, start: string, end: string, days: number
  ) => void
  onMoveTaskWindow: (
    projectId: string, taskId: string, patch: Pick<Task, 'start' | 'end' | 'window'>,
    slots: number
  ) => void
  onMoveMilestone: (projectId: string, milestoneId: string, date: string) => void
  onRenameMilestone: (projectId: string, milestoneId: string, title: string) => Promise<boolean>
  onDeleteMilestone: (projectId: string, milestoneId: string) => void
  onNewMilestone: (projectId: string, date: string, title: string) => Promise<boolean>
}) {
  const fmt = useFormat()
  const m = useMessages()
  const [pop, setPop] = useState<MilestonePop | null>(null)
  const [showInactive, setShowInactive] = useState(false)
  // The overview answers what is still left to do, so finished tasks and milestones stay on the project page;
  // the history view shows everything, finished work included.
  const visibleProjects = useMemo(
    () => showInactive ? rows : rows
      .filter((project) => project.status === ACTIVE_PROJECT)
      .map((project) => ({
        ...project,
        tasks: project.tasks.filter((task) => task.state !== 'done'),
        milestones: project.milestones.filter((milestone) => !milestone.done),
      })),
    [rows, showInactive],
  )
  const closePop = useCallback(() => setPop(null), [])

  const milestonePopover = (
    <FloatingTextEditor
      open={pop !== null}
      anchor={<span className="ganchor" style={{ left: pop?.left ?? 0, top: pop?.top ?? 0 }} />}
      editorKey={pop === null
        ? 'closed'
        : `${pop.kind}/${pop.projectId}/${pop.kind === 'edit' ? pop.milestoneId : ''}/${pop.date}/${pop.left}`}
      title={pop === null
        ? m.project.plan.milestoneMode
        : m.research.overview.milestonePopTitle(pop.kind !== 'edit', fmt.date(pop.date))}
      initialValue={pop?.kind === 'edit' ? pop.title : ''} placeholder={m.project.plan.milestoneNamePlaceholder}
      onSubmit={(title) => pop === null
        ? false
        : pop.kind === 'edit'
          ? onRenameMilestone(pop.projectId, pop.milestoneId, title)
          : onNewMilestone(pop.projectId, pop.date, title)}
      onClose={closePop}
      {...(pop?.kind === 'edit'
        ? { onDelete: () => onDeleteMilestone(pop.projectId, pop.milestoneId) }
        : {})}
    />
  )

  return (
    <TimelineBoard
      projects={visibleProjects}
      className="overview-gantt"
      showProjectNames
      foldable
      onPeriodChange={closePop}
      headerAction={() => (
        <button
          className={`overview-history-toggle${showInactive ? ' on' : ''}`}
          type="button" aria-pressed={showInactive}
          title={showInactive ? m.research.overview.hideHistory : m.research.overview.showHistory}
          onClick={() => { setPop(null); setShowInactive((shown) => !shown) }}
        >{m.research.overview.historyProjects}</button>
      )}
      onLabelClick={(projectId, kind, itemId) => (kind === 'task' && itemId !== undefined
        ? onOpenTask(projectId, itemId) : onOpenProject(projectId))}
      onTaskClick={onOpenTask}
      onMilestoneClick={(projectId, milestoneId, point: TimelinePoint) => {
        const milestone = rows.find((project) => project.id === projectId)
          ?.milestones.find((item) => item.id === milestoneId)
        if (!milestone) return
        setPop({
          kind: 'edit', projectId, milestoneId,
          date: milestone.date, title: milestone.title, ...point,
        })
      }}
      onMilestoneLaneClick={(projectId, date, point) => {
        setPop({ kind: 'new', projectId, date, ...point })
      }}
      onMoveTask={onMoveTask}
      onMoveTaskWindow={onMoveTaskWindow}
      onMoveMilestone={onMoveMilestone}
      canvasOverlay={milestonePopover}
    />
  )
}

/**
 * Research › Overview: A full project view over time. The upper half is the Gantt of the entire project, and the lower half is the numerical summary, what needs to be paid attention to,
 * Project progress, as well as two columns: recent progress and next milestones. The data is obtained through project.overview, and the tasks of the timeline are related to
 * Milestone rescheduling via project.updateTask / updateMilestone, milestone creation and deletion via corresponding methods
 * When writing back, every project entry on the screen jumps to the project on the project screen.
 */
export function ResearchOverview() {
  const fmt = useFormat()
  const m = useMessages()
  const [rows, setRows] = useState<ProjectOverview[] | null>(null)
  const [error, setError] = useState<string | null>(null)
  const { revision } = useVaultRevision()
  const { open: jumpTo } = useJump()
  const banner = useBanner()
  const toast = useToast()
  const reportError = useCallback((e: Error) => setError(e.message), [])
  const write = useVaultWrite()

  useEffect(() => {
    void projectApi.overview().then(setRows).catch(reportError)
  }, [revision, reportError])

  const openProject = useCallback((id: string) => jumpTo('project', id), [jumpTo])
  const openTask = useCallback((id: string, task: string) => jumpTo('project', id, { task }), [jumpTo])

  const moveTask = useCallback((
    projectId: string, taskId: string, start: string, end: string, days: number,
  ) => {
    void write(
      projectApi.updateTask(projectId, taskId, { start, end }),
      { note: m.project.plan.taskMoved(days), notify: toast },
    )
  }, [write, toast, m])

  const moveTaskWindow = useCallback((
    projectId: string, taskId: string,
    patch: Pick<Task, 'start' | 'end' | 'window'>, slots: number,
  ) => {
    void write(
      projectApi.updateTask(projectId, taskId, patch),
      {
        note: m.research.overview.taskWindowMovedHours(slots, Math.abs(slots) * DAY_SLOT_HOURS),
        notify: toast,
      },
    )
  }, [write, toast, m])

  const moveMilestone = useCallback((projectId: string, milestoneId: string, date: string) => {
    void write(
      projectApi.updateMilestone(projectId, milestoneId, { date }),
      { note: m.project.plan.rescheduledTo(fmt.date(date)), notify: toast },
    )
  }, [write, toast, fmt, m])

  const renameMilestone = useCallback((projectId: string, milestoneId: string, title: string) => write(
    projectApi.updateMilestone(projectId, milestoneId, { title }),
    { note: m.project.plan.milestoneUpdated, notify: banner },
  ), [write, banner, m])

  const deleteMilestone = useCallback((projectId: string, milestoneId: string) => {
    void write(
      projectApi.deleteMilestone(projectId, milestoneId),
      { note: m.project.plan.milestoneDeleted, notify: banner },
    )
  }, [write, banner, m])

  const newMilestone = useCallback((projectId: string, date: string, title: string) => write(
    projectApi.createMilestone(projectId, { date, title, done: false }),
    { note: m.project.plan.milestoneCreated, notify: banner },
  ), [write, banner, m])

  return (
    <PageShell>
      <PageHeader>
        <PageTitle>
          {m.research.overview.title(rows?.filter((p) => p.status === ACTIVE_PROJECT).length ?? 0)}
        </PageTitle>
      </PageHeader>
      <PageError error={error} />

      {rows === null
        ? null
        : (
          <PageBody>
            <SectionHeading>{m.research.overview.timelineHeading}</SectionHeading>
            <OverviewGantt
              rows={rows} onOpenProject={openProject} onOpenTask={openTask} onMoveTask={moveTask}
              onMoveTaskWindow={moveTaskWindow}
              onMoveMilestone={moveMilestone} onRenameMilestone={renameMilestone}
              onDeleteMilestone={deleteMilestone} onNewMilestone={newMilestone}
            />
            <SectionHeading>{m.research.overview.statsHeading}</SectionHeading>
            <Stats rows={rows} />
            <DecisionQueue rows={rows} onOpen={openProject} />
            <ProjectProgress rows={rows} onOpen={openProject} />
            <div className="ovcols">
              <div><Recent rows={rows} onOpen={openProject} /></div>
              <div><Upcoming rows={rows} onOpen={openProject} /></div>
            </div>
          </PageBody>
        )}
    </PageShell>
  )
}
